# Generated by Django 3.0.8 on 2021-01-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rambleapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
